# PingDaddyPro Docker Compose Configuration
# GitHub: https://github.com/zaja/pingdaddypro
# Docker Hub: svejedobro/pingdaddypro
# Version: 1.0.3
#
# Default Access Credentials:
# Web Application: http://localhost:5000 (admin / admin123)
# PostgreSQL: localhost:5432 (pingdaddypro / pingdaddypro)

version: '3.8'

networks:
  pingdaddypro-network:
    driver: bridge

services:
  postgres:
    image: postgres:15-alpine
    container_name: pingdaddypro-postgres
    environment:
      POSTGRES_DB: pingdaddypro
      POSTGRES_USER: pingdaddypro
      POSTGRES_PASSWORD: pingdaddypro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - pingdaddypro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pingdaddypro"]
      interval: 10s
      timeout: 5s
      retries: 5

  pingdaddypro:
    image: svejedobro/pingdaddypro:latest
    container_name: pingdaddypro
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://pingdaddypro:pingdaddypro@postgres:5432/pingdaddypro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pingdaddypro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: pingdaddypro-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - pingdaddypro
    restart: unless-stopped
    networks:
      - pingdaddypro-network

volumes:
  postgres_data:

# After running 'docker-compose up -d', you can access the application at:
# http://localhost:5000 or http://YOUR_SERVER_IP:5000
# Default login: admin / admin123
#
# Both installation methods now use the same Docker Hub image:
# - Method 1 (install.sh): svejedobro/pingdaddypro:latest
# - Method 2 (docker-compose): svejedobro/pingdaddypro:latest
